name: taxi_app
description: Taxi booking app with Flutter, Firebase Auth and MockAPI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_messaging: ^14.7.19

  # HTTP клиент
  dio: ^5.4.1

  # State management
  provider: ^6.1.2

  # Локальные уведомления
  flutter_local_notifications: ^17.0.0

  # Хранение сессии
  shared_preferences: ^2.2.2

  # Форматирование дат
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true