// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9EnVHGG_AktiBOu_SXqN2LR1JSTVI1ug',
    appId: '1:934475687484:web:49423c9e3063a9955c4539',
    messagingSenderId: '934475687484',
    projectId: 'flutter2-66192',
    authDomain: 'flutter2-66192.firebaseapp.com',
    storageBucket: 'flutter2-66192.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-tFWVdIjkV-UOX6yFiql-vBkVd3Y3Zzc',
    appId: '1:934475687484:android:f776f73e01d824455c4539',
    messagingSenderId: '934475687484',
    projectId: 'flutter2-66192',
    storageBucket: 'flutter2-66192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT7fBfsBDiFXKnk07kyt3ARFoC9Dr2biE',
    appId: '1:934475687484:ios:11e41acaba4a771e5c4539',
    messagingSenderId: '934475687484',
    projectId: 'flutter2-66192',
    storageBucket: 'flutter2-66192.firebasestorage.app',
    androidClientId: '934475687484-ikioao2ppvp6kn7vdtpbag2q9lmoqoej.apps.googleusercontent.com',
    iosClientId: '934475687484-f3tsl2njcncitaifgfti38dcenlq5c2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT7fBfsBDiFXKnk07kyt3ARFoC9Dr2biE',
    appId: '1:934475687484:ios:11e41acaba4a771e5c4539',
    messagingSenderId: '934475687484',
    projectId: 'flutter2-66192',
    storageBucket: 'flutter2-66192.firebasestorage.app',
    androidClientId: '934475687484-ikioao2ppvp6kn7vdtpbag2q9lmoqoej.apps.googleusercontent.com',
    iosClientId: '934475687484-f3tsl2njcncitaifgfti38dcenlq5c2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9EnVHGG_AktiBOu_SXqN2LR1JSTVI1ug',
    appId: '1:934475687484:web:ee7285c19a7243ac5c4539',
    messagingSenderId: '934475687484',
    projectId: 'flutter2-66192',
    authDomain: 'flutter2-66192.firebaseapp.com',
    storageBucket: 'flutter2-66192.firebasestorage.app',
  );

}